---
- name: Both gather facts in signle file
  hosts: all
  become: true
  gather_facts: yes
  tasks:
   - name: this is first task without gather fact
     debug:
       msg: "{{ ansible_os_family }}"
     gather_facts: no
...
