---
- name: Both gather facts in signle file
  hosts: all
  become: true
  gather_facts: true
  tasks:
   - name: this is first task with gather fact
     debug:
       msg: "{{ ansible_os_family }}"
     gather_facts: false
   - name: this is second task without gather fact

...
